package ddl

import (
	"context"
)

type DDL struct {
	Indent string
	Header []string
	Stmts  []Stmt
}

func NewDDL(_ context.Context) *DDL {
	return &DDL{
		Indent: "    ",
		Header: []string{
			"Code generated by ddlgen. DO NOT EDIT.",
			"",
		},
	}
}

type Stmt interface {
	GetSourceFile() string
	GetSourceLine() int

	private()
}
