run:
  skip-files:
    - cmd/sandbox/main.go
    - internal/integrationtest/samples/.*\.go
  modules-download-mode: readonly
  allow-parallel-runners: true

# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - depguard # unnecessary
    - dupl # 行き過ぎた DRY を助長するため無効化
    - exhaustruct # https://github.com/GaijinEntertainment/go-exhaustruct
    - exhaustivestruct # https://github.com/mbilski/exhaustivestruct
    - gci # unnecessary
    - godox # unnecessary
    - golint # deprecated https://github.com/golang/lint
    - gomnd # https://github.com/tommy-muehle/go-mnd
    - gosmopolitan # unnecessary
    - ifshort # for readability
    - interfacebloat # unnecessary
    - interfacer # deprecated https://github.com/mvdan/interfacer
    - lll # unnecessary
    - maligned # deprecated https://github.com/mdempsky/maligned
    - nlreturn # ignore "return with no blank line before"
    - nolintlint # unnecessary
    - nonamedreturns # unnecessary
    - nosnakecase # for environment variable key
    - varnamelen # unnecessary
    - wsl # ignore "declarations should never be cuddled"

linters-settings:
  godot:
    period: false
  goimports:
    local-prefixes: "github.com/iriam/iriam-automov3"
  wrapcheck:
    ignoreSigs:
      - func errors.New(text string) error
      - func fmt.Errorf(format string, a ...any) error
      - func fmt.Errorf(format string, a ...interface{}) error
      - func github.com/kunitsucom/util.go/errors.Errorf(format string, a ...interface{}) error


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - cyclop
        - dupl
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - goerr113
        - ireturn
        - maintidx
        - noctx
        - varnamelen
        - wrapcheck
