-- Code generated by ddlgen. DO NOT EDIT.
--
-- Date: 2023-10-27T19:33:00Z
--

-- source: samples/success_SuccessParen.go:8
-- SuccessParen
CREATE TABLE `SuccessParens` (
    -- ID is a primary key of SuccessParen
    -- ID requires uuid
    `Id`          STRING(36) NOT NULL,
    -- Description is a description of SuccessParen
    `Description` STRING(1024) NOT NULL
)

-- source: samples/success_SuccessParen.go:21
-- SuccessParenTwo
CREATE TABLE `SuccessParenTwos` (
    -- ID is a primary key of SuccessParenTwo
    -- ID requires uuid
    `Id`             STRING(36) NOT NULL,
    -- SuccessParenID is a foreign key to SuccessParen.ID
    `SuccessParenId` STRING(36) NOT NULL,
    -- Description is a description of SuccessParenTwo
    `Description`    STRING(1024) NOT NULL,
    FOREIGN KEY (`SuccessParenId`) REFERENCES SuccessParens(`Id`)
)

-- source: samples/success_SuccessParen.go:34
-- SuccessParenThree
CREATE TABLE SuccessParenThree (
    -- ID is a primary key of SuccessParenThree
    -- ID requires uuid
    `Id`          STRING(36) NOT NULL,
    -- Description is a description of SuccessParenThree
    `Description` STRING(1024) NOT NULL
)

-- source: samples/success_SuccessParen.go:45
CREATE TABLE `SuccessParenFour` (
    -- ID is a primary key of SuccessParenFour
    -- ID requires uuid
    `Id`             STRING(36) NOT NULL,
    -- SuccessParenID is a foreign key to SuccessParen.ID
    `SuccessParenId` STRING(36) NOT NULL,
    -- Description is a description of SuccessParenFour
    `Description`    STRING(1024) NOT NULL,
    FOREIGN KEY (`SuccessParenId`) REFERENCES SuccessParens(`Id`)
)

-- source: samples/success_SuccessRoot.go:9
-- SuccessRoot
CREATE TABLE success_roots (
    -- ID is a primary key of SuccessRoot
    -- ID requires uuid
    `Id`          STRING(36) NOT NULL,
    -- Description is a description of SuccessRoot
    `Description` STRING(1024) NOT NULL
)

-- source: samples/success_SuccessRoot.go:22
-- SuccessRootTwo
CREATE TABLE success_root_twos (
    -- ID is a primary key of SuccessRootTwo
    -- ID requires uuid
    `Id`              STRING(36) NOT NULL,
    -- SuccessRootID is a foreign key to SuccessRoot.ID
    `success_root_id` STRING(36) NOT NULL,
    -- Description is a description of SuccessRootTwo
    `Description`     STRING(1024) NOT NULL,
    FOREIGN KEY (success_root_id) REFERENCES success_roots(`Id`)
)

-- source: samples/success_SuccessUnformattedFile.go:6
-- SuccessUnformattedFile
CREATE TABLE success_unformatted_files (
    --  ID is a primary key of SuccessUnformattedFile
    `Id` STRING(36) NOT NULL
)
