name: go-lint
#     ^^^^^^^
# https://github.com/kunitsucom/ddlgen/workflows/go-lint/badge.svg
#                                                ^^^^^^^

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/pull_request_template.md'
      - '.github/release.yml'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/pull_request_template.md'
      - '.github/release.yml'
      - '**.md'
  workflow_dispatch:
    inputs: {}

# NOTE: If commit & push continuously, cancel the workflow other than the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: .

defaults:
  run:
    shell: bash

jobs:
  go-lint: # NOTE: for Branch protection rule `Status checks that are required.`
    name: Run golangci-lint
    runs-on: ubuntu-latest # ref. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      - uses: actions/checkout@v4
      - name: DEBUG
        run: |
          cat <<'DEBUG_DOC'
          == DEBUG =======================================================
          github.ref: ${{ github.ref }}
          github.event_name: ${{ github.event_name }}
          -- toJSON(github.event.inputs) ---------------------------------
          ${{ toJSON(github.event.inputs) }}
          -- toJSON(github) ----------------------------------------------
          ${{ toJSON(github) }}
          ================================================================
          DEBUG_DOC
        shell: bash
      - name: actions/cache for versenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/versenv
          key: versenv-${{ runner.os }}-${{ hashFiles('**/.versenv.env') }}
          restore-keys: |
            versenv-${{ runner.os }}-
      - name: Add GITHUB_PATH, GITHUB_ENV
        run: |
          # Update GITHUB_PATH
          cat <<GITHUB_PATH >> $GITHUB_PATH
          ${PWD}/.local/bin
          ${PWD}/${{ env.WORKDIR }}/.local/bin
          ${PWD}/.bin
          GITHUB_PATH
          # Update GITHUB_ENV
          grep -Ev '^\s*$|^\s*#' .versenv.env >> $GITHUB_ENV
      - name: Setup versenv
        run: |
          # Setup versenv
          make versenv
          direnv allow ${{ env.WORKDIR }}
      - uses: actions/setup-go@v4 # ref. https://github.com/actions/setup-go#usage
        id: setup-go
        with:
          cache: false
          go-version-file: ${{ env.WORKDIR }}/go.mod
      - name: Get Golang info
        id: golang-info
        run: |
          echo "GOVERSION=$(go version | cut -d' ' -f3)" >> "$GITHUB_OUTPUT"
          echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
      - name: actions/cache for go
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ${{ steps.golang-info.outputs.GOCACHE }}
          key: ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-
            ${{ runner.os }}-go-
      - name: Run go mod tidy
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        env:
          DEBIAN_FRONTEND: noninteractive
          # GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        working-directory: ${{ env.WORKDIR }}
        run: |
          set -Eeux -o pipefail
          direnv allow .
          direnv exec . bash -Eeux -o pipefail -c 'echo "${GOPRIVATE:-}${GOPRIVATE+,}" | while read -d , -r LINE; do echo "set git config: ${LINE}"; git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@${LINE}".insteadOf "https://${LINE}"; done'
          direnv exec . go mod tidy
          git diff --exit-code go.mod go.sum
      - uses: golangci/golangci-lint-action@v3.7.0 # ref. https://github.com/golangci/golangci-lint-action#how-to-use
        with:
          working-directory: ${{ env.WORKDIR }}
          args: --timeout=600s
          version: latest # or v${{ env.GOLANGCI_LINT_VERSION }}
